# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a940b740b3f97aefd281f91a4dddbe4912f7dd7f70bc1db8ab8ce74df07d69840e715c88c3030a500d38cb3e099675c27ba99b8bf73b4151c7633603cd3e8829

test:
  secret_key_base: 3c3875839c875001efa3bd07625a61f1a716721c7cef4093251262fa0a5eef8b5bf06083d564e27870bf8ac16e204c35d1c7100f3ca2eb07f90a8d6c2deb8477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
